// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKrr9n1i6RfrEhnFbpXzqnx0NKeWCkJY',
    appId: '1:280393424640:web:91d071498ce417939f9de5',
    messagingSenderId: '280393424640',
    projectId: 'resume2webai',
    authDomain: 'resume2webai.firebaseapp.com',
    storageBucket: 'resume2webai.firebasestorage.app',
    measurementId: 'G-K3B1ZQ6RSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgnltnjgSCszDZGLs0_t8Tta0JZagR3ys',
    appId: '1:280393424640:android:58a1d2c9292062c79f9de5',
    messagingSenderId: '280393424640',
    projectId: 'resume2webai',
    storageBucket: 'resume2webai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMQDwQxArqP60YCtd-fp4dElJEzglRrPE',
    appId: '1:280393424640:ios:8c4f8308980517a89f9de5',
    messagingSenderId: '280393424640',
    projectId: 'resume2webai',
    storageBucket: 'resume2webai.firebasestorage.app',
    iosClientId: '280393424640-sfhgoan7v1f5g5jq91r9e1uneiqd6jdq.apps.googleusercontent.com',
    iosBundleId: 'com.sadanand1.resume2webai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMQDwQxArqP60YCtd-fp4dElJEzglRrPE',
    appId: '1:280393424640:ios:8c4f8308980517a89f9de5',
    messagingSenderId: '280393424640',
    projectId: 'resume2webai',
    storageBucket: 'resume2webai.firebasestorage.app',
    iosClientId: '280393424640-sfhgoan7v1f5g5jq91r9e1uneiqd6jdq.apps.googleusercontent.com',
    iosBundleId: 'com.sadanand1.resume2webai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBKrr9n1i6RfrEhnFbpXzqnx0NKeWCkJY',
    appId: '1:280393424640:web:dd4886e070f7b4589f9de5',
    messagingSenderId: '280393424640',
    projectId: 'resume2webai',
    authDomain: 'resume2webai.firebaseapp.com',
    storageBucket: 'resume2webai.firebasestorage.app',
    measurementId: 'G-TTDYWCYHGQ',
  );

}